# config.yaml
#消息队列配置
rocketmq:
  grpc_server: "localhost:50051"
  nameserver: "192.168.172.214:9876"  # RocketMQ NameServer地址
  topic: "asr_transfer_topic"            # 订阅的主题
  consumer_group: "asr_consumer_group"  # 消费者组
  tag: "tag_asr_transfer_txt"                      # 订阅的标签
  # 添加生产者配置
  producer_group: "asr_producer_group" # 生产者组
  send_topic: "asr_result_topic"       # 发送结果的主题
# 线程池配置
thread_pool:
  max_workers: 10
# MinIO配置
minio:
  endpoint: "192.168.172.214:9998"
  access_key: "tiger"
  secret_key: "tiger123"
  secure: false  # 是否使用HTTPS
# Whisper模型配置
whisper:
  model_type: "large-v2"  # 可选: tiny, base, small, medium, large-v1,large-v2,large-v3,large,large-v3-turbo,turbo
  device: "cuda"  # 可选: cpu, cuda
  batch_size: 16  # 批处理大小
  compute_type: "float16"  # 可选: float16, int8_float16, int8
  download_root: "/data2/hf_cache/whisper"  # whisper模型下载路径，废弃
# 说话人分离配置
diarization:
  use_diarization: true  # 是否启用说话人分离
  model: "pyannote/speaker-diarization-3.1"  # 说话人分离模型
  hf_token: "xxxxxxxx"  # Hugging Face访问令牌
  download_root: "/data2/hf_cache/pyannote"  # pyannote模型下载路径，废弃