rocketmq:
  nameserver: "127.0.0.1:9876"
  topic: "TestTopic"
  group: "TestGroup"
  retry: 2
server:
  host: "0.0.0.0"
  port: 8080
python:
  callback: "http://127.0.0.1:5000/mq_callback"
log:
  level: "info"
