version: '3.8'

services:
  # RocketMQ Gateway Service
  rocketmq-gateway:
    build: .
    container_name: rocketmq-gateway
    ports:
      - "8080:8080"
    environment:
      - RMC_SERVER_HOST=0.0.0.0
      - RMC_SERVER_PORT=8080
      - RMC_ROCKETMQ_NAMESERVER=rocketmq:9876
      - RMC_PYTHON_CALLBACK=http://python-service:5000/mq_callback
      - RMC_LOG_LEVEL=info
    depends_on:
      - rocketmq
    networks:
      - rocketmq-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # RocketMQ NameServer
  rocketmq:
    image: apache/rocketmq:4.9.4
    container_name: rocketmq-nameserver
    ports:
      - "9876:9876"
    environment:
      - JAVA_OPT_EXT=-Xms512m -Xmx512m -Xmn128m
    command: sh mqnamesrv
    networks:
      - rocketmq-network
    restart: unless-stopped

  # RocketMQ Broker
  rocketmq-broker:
    image: apache/rocketmq:4.9.4
    container_name: rocketmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
    environment:
      - NAMESRV_ADDR=rocketmq:9876
      - JAVA_OPT_EXT=-Xms512m -Xmx512m -Xmn128m
    command: sh mqbroker -c /opt/rocketmq-4.9.4/conf/broker.conf
    depends_on:
      - rocketmq
    networks:
      - rocketmq-network
    restart: unless-stopped

  # Python Service Example (Optional)
  python-service:
    build: ./python_client
    container_name: python-service
    ports:
      - "5000:5000"
    environment:
      - ROCKETMQ_GATEWAY_HOST=rocketmq-gateway
      - ROCKETMQ_GATEWAY_PORT=8080
    depends_on:
      - rocketmq-gateway
    networks:
      - rocketmq-network
    restart: unless-stopped

networks:
  rocketmq-network:
    driver: bridge

volumes:
  rocketmq-logs:
  rocketmq-store:
